[package]
name = "rust-fxr-reloader"
version = "0.4.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
windows = { version = "0.48.0", features = ["Win32_System_LibraryLoader", "Win32_Foundation"] }
