[package]
name = "fxr-reloader-gui"
version = "0.4.0"
edition = "2021"

[dependencies]
iced = { version = "0.10.0", features = ["image", "smol"] }
rfd = "0.11"
image = "0.24"
sysinfo = "0.28"
dll-syringe = { workspace = true, features = ["payload-utils"]}